// Code generated by protoc-gen-go.
// source: partition.proto
// DO NOT EDIT!

/*
Package partition is a generated protocol buffer package.

It is generated from these files:
	partition.proto

It has these top-level messages:
	DenunciateRequest
	AlivenessResponse
	Dummy
	Member
	PartitionsOfMember
	BackupPartitionsOfMember
	PartitionTable
*/
package partition

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DenunciateRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
}

func (m *DenunciateRequest) Reset()                    { *m = DenunciateRequest{} }
func (m *DenunciateRequest) String() string            { return proto.CompactTextString(m) }
func (*DenunciateRequest) ProtoMessage()               {}
func (*DenunciateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DenunciateRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type AlivenessResponse struct {
	Birthdate int64 `protobuf:"varint,1,opt,name=birthdate" json:"birthdate,omitempty"`
}

func (m *AlivenessResponse) Reset()                    { *m = AlivenessResponse{} }
func (m *AlivenessResponse) String() string            { return proto.CompactTextString(m) }
func (*AlivenessResponse) ProtoMessage()               {}
func (*AlivenessResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AlivenessResponse) GetBirthdate() int64 {
	if m != nil {
		return m.Birthdate
	}
	return 0
}

type Dummy struct {
}

func (m *Dummy) Reset()                    { *m = Dummy{} }
func (m *Dummy) String() string            { return proto.CompactTextString(m) }
func (*Dummy) ProtoMessage()               {}
func (*Dummy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Member struct {
	Address   string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Birthdate int64  `protobuf:"varint,2,opt,name=birthdate" json:"birthdate,omitempty"`
}

func (m *Member) Reset()                    { *m = Member{} }
func (m *Member) String() string            { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()               {}
func (*Member) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Member) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Member) GetBirthdate() int64 {
	if m != nil {
		return m.Birthdate
	}
	return 0
}

type PartitionsOfMember struct {
	Partitions []int32 `protobuf:"varint,1,rep,packed,name=partitions" json:"partitions,omitempty"`
}

func (m *PartitionsOfMember) Reset()                    { *m = PartitionsOfMember{} }
func (m *PartitionsOfMember) String() string            { return proto.CompactTextString(m) }
func (*PartitionsOfMember) ProtoMessage()               {}
func (*PartitionsOfMember) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PartitionsOfMember) GetPartitions() []int32 {
	if m != nil {
		return m.Partitions
	}
	return nil
}

type BackupPartitionsOfMember struct {
	Partitions []int32 `protobuf:"varint,1,rep,packed,name=partitions" json:"partitions,omitempty"`
}

func (m *BackupPartitionsOfMember) Reset()                    { *m = BackupPartitionsOfMember{} }
func (m *BackupPartitionsOfMember) String() string            { return proto.CompactTextString(m) }
func (*BackupPartitionsOfMember) ProtoMessage()               {}
func (*BackupPartitionsOfMember) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *BackupPartitionsOfMember) GetPartitions() []int32 {
	if m != nil {
		return m.Partitions
	}
	return nil
}

type PartitionTable struct {
	Partitions               map[int32]string                     `protobuf:"bytes,1,rep,name=partitions" json:"partitions,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Members                  map[string]*PartitionsOfMember       `protobuf:"bytes,2,rep,name=members" json:"members,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Backups                  map[int32]string                     `protobuf:"bytes,3,rep,name=backups" json:"backups,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BackupPartitionsOfMember map[string]*BackupPartitionsOfMember `protobuf:"bytes,4,rep,name=backupPartitionsOfMember" json:"backupPartitionsOfMember,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Sorted                   []*Member                            `protobuf:"bytes,5,rep,name=sorted" json:"sorted,omitempty"`
}

func (m *PartitionTable) Reset()                    { *m = PartitionTable{} }
func (m *PartitionTable) String() string            { return proto.CompactTextString(m) }
func (*PartitionTable) ProtoMessage()               {}
func (*PartitionTable) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PartitionTable) GetPartitions() map[int32]string {
	if m != nil {
		return m.Partitions
	}
	return nil
}

func (m *PartitionTable) GetMembers() map[string]*PartitionsOfMember {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *PartitionTable) GetBackups() map[int32]string {
	if m != nil {
		return m.Backups
	}
	return nil
}

func (m *PartitionTable) GetBackupPartitionsOfMember() map[string]*BackupPartitionsOfMember {
	if m != nil {
		return m.BackupPartitionsOfMember
	}
	return nil
}

func (m *PartitionTable) GetSorted() []*Member {
	if m != nil {
		return m.Sorted
	}
	return nil
}

func init() {
	proto.RegisterType((*DenunciateRequest)(nil), "partition.DenunciateRequest")
	proto.RegisterType((*AlivenessResponse)(nil), "partition.AlivenessResponse")
	proto.RegisterType((*Dummy)(nil), "partition.Dummy")
	proto.RegisterType((*Member)(nil), "partition.Member")
	proto.RegisterType((*PartitionsOfMember)(nil), "partition.PartitionsOfMember")
	proto.RegisterType((*BackupPartitionsOfMember)(nil), "partition.BackupPartitionsOfMember")
	proto.RegisterType((*PartitionTable)(nil), "partition.PartitionTable")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Partition service

type PartitionClient interface {
	Aliveness(ctx context.Context, in *Dummy, opts ...grpc.CallOption) (*AlivenessResponse, error)
	DenunciateForMember(ctx context.Context, in *DenunciateRequest, opts ...grpc.CallOption) (*Dummy, error)
	SetPartitionTable(ctx context.Context, in *PartitionTable, opts ...grpc.CallOption) (*Dummy, error)
}

type partitionClient struct {
	cc *grpc.ClientConn
}

func NewPartitionClient(cc *grpc.ClientConn) PartitionClient {
	return &partitionClient{cc}
}

func (c *partitionClient) Aliveness(ctx context.Context, in *Dummy, opts ...grpc.CallOption) (*AlivenessResponse, error) {
	out := new(AlivenessResponse)
	err := grpc.Invoke(ctx, "/partition.Partition/Aliveness", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partitionClient) DenunciateForMember(ctx context.Context, in *DenunciateRequest, opts ...grpc.CallOption) (*Dummy, error) {
	out := new(Dummy)
	err := grpc.Invoke(ctx, "/partition.Partition/DenunciateForMember", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partitionClient) SetPartitionTable(ctx context.Context, in *PartitionTable, opts ...grpc.CallOption) (*Dummy, error) {
	out := new(Dummy)
	err := grpc.Invoke(ctx, "/partition.Partition/SetPartitionTable", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Partition service

type PartitionServer interface {
	Aliveness(context.Context, *Dummy) (*AlivenessResponse, error)
	DenunciateForMember(context.Context, *DenunciateRequest) (*Dummy, error)
	SetPartitionTable(context.Context, *PartitionTable) (*Dummy, error)
}

func RegisterPartitionServer(s *grpc.Server, srv PartitionServer) {
	s.RegisterService(&_Partition_serviceDesc, srv)
}

func _Partition_Aliveness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Dummy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartitionServer).Aliveness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/partition.Partition/Aliveness",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartitionServer).Aliveness(ctx, req.(*Dummy))
	}
	return interceptor(ctx, in, info, handler)
}

func _Partition_DenunciateForMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DenunciateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartitionServer).DenunciateForMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/partition.Partition/DenunciateForMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartitionServer).DenunciateForMember(ctx, req.(*DenunciateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Partition_SetPartitionTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartitionTable)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartitionServer).SetPartitionTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/partition.Partition/SetPartitionTable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartitionServer).SetPartitionTable(ctx, req.(*PartitionTable))
	}
	return interceptor(ctx, in, info, handler)
}

var _Partition_serviceDesc = grpc.ServiceDesc{
	ServiceName: "partition.Partition",
	HandlerType: (*PartitionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Aliveness",
			Handler:    _Partition_Aliveness_Handler,
		},
		{
			MethodName: "DenunciateForMember",
			Handler:    _Partition_DenunciateForMember_Handler,
		},
		{
			MethodName: "SetPartitionTable",
			Handler:    _Partition_SetPartitionTable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "partition.proto",
}

func init() { proto.RegisterFile("partition.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 448 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x94, 0xdf, 0x8a, 0xd3, 0x40,
	0x14, 0xc6, 0x37, 0x8d, 0x69, 0xc9, 0xd9, 0xc5, 0xdd, 0x8c, 0x5e, 0x8c, 0x61, 0x57, 0x24, 0x82,
	0xec, 0x5e, 0xb8, 0x60, 0x2b, 0xa8, 0x85, 0x42, 0x2d, 0x55, 0xf1, 0x42, 0x94, 0xd1, 0x1b, 0x2f,
	0x93, 0xe6, 0x88, 0xa1, 0xcd, 0x1f, 0x67, 0x26, 0x85, 0x3e, 0xa1, 0x8f, 0xe0, 0xeb, 0x48, 0x27,
	0xff, 0xa6, 0x4d, 0x63, 0x71, 0xef, 0x32, 0xc3, 0xf9, 0x7e, 0xe7, 0x9b, 0x2f, 0x73, 0x06, 0xce,
	0x33, 0x9f, 0xcb, 0x48, 0x46, 0x69, 0x72, 0x9b, 0xf1, 0x54, 0xa6, 0xc4, 0xae, 0x37, 0xbc, 0xe7,
	0xe0, 0xcc, 0x31, 0xc9, 0x93, 0x45, 0xe4, 0x4b, 0x64, 0xf8, 0x2b, 0x47, 0x21, 0x09, 0x85, 0x81,
	0x1f, 0x86, 0x1c, 0x85, 0xa0, 0xc6, 0x13, 0xe3, 0xda, 0x66, 0xd5, 0xd2, 0x7b, 0x01, 0xce, 0xdb,
	0x55, 0xb4, 0xc6, 0x04, 0x85, 0x60, 0x28, 0xb2, 0x34, 0x11, 0x48, 0x2e, 0xc1, 0x0e, 0x22, 0x2e,
	0x7f, 0x86, 0xbe, 0x44, 0x25, 0x30, 0x59, 0xb3, 0xe1, 0x0d, 0xc0, 0x9a, 0xe7, 0x71, 0xbc, 0xf1,
	0xa6, 0xd0, 0xff, 0x84, 0x71, 0x80, 0xbc, 0x9b, 0xbf, 0x8b, 0xea, 0xed, 0xa3, 0x5e, 0x02, 0xf9,
	0x52, 0x39, 0x17, 0x9f, 0x7f, 0x94, 0xb4, 0xc7, 0x00, 0xf5, 0x79, 0xb6, 0x40, 0xf3, 0xda, 0x62,
	0xda, 0x8e, 0x37, 0x06, 0x3a, 0xf3, 0x17, 0xcb, 0x3c, 0xbb, 0x83, 0xf6, 0xb7, 0x05, 0xf7, 0x6b,
	0xd9, 0x37, 0x3f, 0x58, 0x21, 0xf9, 0xd8, 0x92, 0x9c, 0x0e, 0x6f, 0x6e, 0x9b, 0x88, 0x77, 0xcb,
	0x9b, 0xa5, 0x78, 0x97, 0x48, 0xbe, 0xd1, 0xe9, 0x64, 0x0a, 0x83, 0x58, 0xf9, 0x10, 0xb4, 0xa7,
	0x38, 0xcf, 0xba, 0x39, 0x85, 0xe1, 0x12, 0x52, 0xc9, 0xb6, 0x84, 0x40, 0x9d, 0x4d, 0x50, 0xf3,
	0x18, 0xa1, 0x08, 0xa1, 0x22, 0x94, 0x32, 0x22, 0x80, 0x06, 0x1d, 0xe9, 0xd0, 0x7b, 0x0a, 0xf9,
	0xea, 0x18, 0xb2, 0xad, 0x2c, 0x7a, 0x74, 0x82, 0xc9, 0x0d, 0xf4, 0x45, 0xca, 0x25, 0x86, 0xd4,
	0x52, 0x2d, 0x1c, 0xad, 0x45, 0x51, 0xc2, 0xca, 0x02, 0x77, 0x02, 0xe7, 0x7b, 0x11, 0x92, 0x0b,
	0x30, 0x97, 0xb8, 0x51, 0x57, 0xc7, 0x62, 0xdb, 0x4f, 0xf2, 0x10, 0xac, 0xb5, 0xbf, 0xca, 0x8b,
	0x2b, 0x63, 0xb3, 0x62, 0x31, 0xee, 0xbd, 0x36, 0xdc, 0xef, 0x70, 0xa6, 0x27, 0xa7, 0x6b, 0xed,
	0x42, 0x3b, 0xd2, 0xb5, 0xa7, 0xc3, 0xab, 0x43, 0xa7, 0xad, 0x9d, 0xeb, 0xe8, 0x31, 0x9c, 0xe9,
	0x91, 0xfe, 0x97, 0xad, 0x0c, 0xae, 0xfe, 0x99, 0xdd, 0x01, 0x9f, 0x6f, 0x76, 0x7d, 0x3e, 0xd5,
	0x7c, 0x76, 0xa1, 0xb4, 0x8e, 0xc3, 0x3f, 0x06, 0xd8, 0x75, 0x05, 0x99, 0x80, 0x5d, 0xcf, 0x31,
	0xb9, 0xd0, 0x50, 0x6a, 0x54, 0xdd, 0x4b, 0x6d, 0xa7, 0x35, 0xef, 0xde, 0x09, 0xf9, 0x00, 0x0f,
	0x9a, 0x57, 0xe3, 0x7d, 0xca, 0xcb, 0xdf, 0xaa, 0xcb, 0x5a, 0xaf, 0x8a, 0xdb, 0x6a, 0xe3, 0x9d,
	0x90, 0x19, 0x38, 0x5f, 0x51, 0xee, 0x4d, 0xd8, 0xa3, 0xce, 0x0b, 0x77, 0x88, 0x11, 0xf4, 0xd5,
	0xa3, 0x36, 0xfa, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x07, 0xaa, 0xb4, 0x36, 0xe7, 0x04, 0x00, 0x00,
}
